openai_models:
  gpt_4o:
    model_name: gpt-4o
    deployment: gpt-4o
    api_version: "2024-12-01-preview"
    max_tokens: 12288
    temperature: 0.0
    top_p: 1.0

  gpt_4o_mini:
    model_name: gpt-4o-mini
    deployment: gpt-4o-mini
    api_version: "2024-12-01-preview"
    max_tokens: 12288
    temperature: 0.7
    top_p: 1.0

  embeddings:
    model_name: text-embedding-ada-002
    deployment: text-embedding-ada-002
    api_version: "2024-12-01-preview"

azure_ai_search:
  index_name: non-template-clauses-index
